// File generated by FlutterFire CLI & configured for freelancehub-67192.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Shares iOS project config
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQo8-5iakWseaDvFEtZW5asxTVxuVdslM',
    appId: '1:532799226637:web:25c889ac47df0c5fa22644',
    messagingSenderId: '532799226637',
    projectId: 'freelancehub-67192',
    authDomain: 'freelancehub-67192.firebaseapp.com',
    databaseURL:
        'https://freelancehub-67192-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelancehub-67192.firebasestorage.app',
    measurementId: 'G-JPQ5CLEHXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLFFV1D3nFKvOgtxKgOHLrCz-mxTmBHI',
    appId: '1:532799226637:android:507611c059e04882a22644',
    messagingSenderId: '532799226637',
    projectId: 'freelancehub-67192',
    databaseURL:
        'https://freelancehub-67192-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelancehub-67192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTTUJHDuhBhAkMmKvmpVq4owincrmh_DQ',
    appId: '1:532799226637:ios:efb15f27e982551fa22644',
    messagingSenderId: '532799226637',
    projectId: 'freelancehub-67192',
    databaseURL:
        'https://freelancehub-67192-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelancehub-67192.firebasestorage.app',
    iosBundleId: 'com.example.freelancehub',
  );
}
